### ISSUE TITLE
Help with decompilation

### ISSUE THREAD

**Issue by FreedomLabsIO** [jpstotz/Wireshark-Fido2-CTAP#1]
Hello @jpstotz , sorry to use this space for this purpose.

I'm trying to decompile the Whatsapp.apk to make one small modification for personal usage but still no success. I tried using https://github.com/skylot/jadx but get lots of errors in the .java files. I also tried apktool but it only generates the ".smali" files.

Really glad if you can point me into the right direction.

Thanks!

**Comment by jpstotz** [comment]
In my opinion Jadx is not usable for decompiling large apps. If you want to modify an app you have to use apktool and learn Smali syntax.

**Comment by FreedomLabsIO** [comment]
> In my opinion Jadx is not usable for decompiling large apps. If you want to modify an app you have to use apktool and learn Smali syntax.

Ok thanks for the reply and sorry to ask (just by curiosity), but if jadx is not usable for decompiling large apps like WhatsApp, why the questions about decompiling WhatsApp in the jadx project?

**Comment by jpstotz** [comment]
If you want you can load large apps into Jadx but you have to consider that only may be 95% of the code can be decompiled and another 5% are decompiled wrong (just a guess). So if you are just searching for a specific code part Jadx is the tool for you.

**Comment by FreedomLabsIO** [comment]
> If you want you can load large apps into Jadx but you have to consider that only may be 95% of the code can be decompiled and another 5% are decompiled wrong (just a guess). So if you are just searching for a specific code part Jadx is the tool for you.

Ok, thanks!
